version: "2"
checks:
    method-lines:
        config:
            threshold: 100
    argument-count:
        enabled: false
plugins:
    rubocop:
        enabled: true
    eslint:
        enabled: true
exclude_patterns:
    - "bin/"
    - "config/"
    - "ui/"
    - "**/node_modules/"
    - "**/test/"
    - "**/tests/"